### PR TITLE
Make pysapcompress C extension Python 2/3 compatible

### PR DESCRIPTION
**Pull request by okuuva**
Ported unit tests for it as well while I was at it. Solves #25 and two cards from Python 2-3 project. Couldn't figure out how to refer to them in PR :/

### CODE REVIEW

**Comment by okuuva** [comment]
Hmm, no idea why Travis builds fail, pip discovery seems to work but still keep getting `install: missing destination file operand after ‘.’` :/

**Comment by martingalloar** [comment]
Changes looks good on my dev too!

The `python2-3` branch was already failing, the set of the `PIP` variable was in a previous script context. Can you rebase https://github.com/CoreSecurity/pysap/commit/a9c11e0b6bb6b62ed3c454968fe4a3bda2d1117b from it and update your branch?

**Comment by okuuva** [comment]
Ah, that explains it. I'm not that familiar with Travis. Rebased on a9c11e0b6bb6b62ed3c454968fe4a3bda2d1117b

**Comment by okuuva** [comment]
Ok, now only Python 3 builds fail, but that was expected as there still are parts that haven't been ported.

**Pull request merged**
